### ISSUE TITLE
MBCord does not accept servers with no port

### ISSUE THREAD

**Issue by KakarottoCake** [oonqt/MBCord#42]
Using MBCord for a server that does not publically announce it's port, forcing me to fill in all fields when not applicable for this particular server
![image](https://user-images.githubusercontent.com/61133727/185337135-cb2df11e-cc84-4dca-8775-97a2bd98cac6.png)

**Comment by SandwichFox** [comment]
Does your server have an https:// or http:// connection? If its Https:// it's port 443 and for http:// it's port 80

**Comment by KakarottoCake** [comment]
> Does your server have an https:// or http:// connection? If its Https:// it's port 443 and for http:// it's port 80

I tried both of those with no luck, despite it working when typing it in the browser.

**Comment by dragonfire5020** [comment]
I have the same issue, neither 443, 80, 8096 nor 8920 are working.
It seems like its kind of hard coded not to accept 443 without trying, because when I am trying that port I'll get an instant error, however with 8096 it take some time.
Is there a fix available?

**Comment by KakarottoCake** [comment]
I'm assuming that since it was closed it was fixed?
________________________________

**Comment by oonqt** [comment]
It was closed because it does not exist

**Comment by KakarottoCake** [comment]
Hm, that's odd. After testing it again, it does exist. Are you sure?
________________________________

**Comment by KakarottoCake** [comment]
@dragonfire5020 was having my exact issue as well, where all ports would instantly error out and the 8096 port would take a minute to error out but it still won't work.

**Comment by KakarottoCake** [comment]
@dragonfire5020 was having my exact issue as well, where all ports would instantly error out and the 8096 port would take a minute to error out but it still won't work.

**Comment by oonqt** [comment]
However, destroyed issue. No longer effective in combat

**Comment by KakarottoCake** [comment]
But it's still an issue. Closing it or not the problem still exists

**Comment by oonqt** [comment]
Hello, no longer issue. No fact will change the fact that this issue has been closed. 🤓

**Comment by KakarottoCake** [comment]
@oonqt no fact will change that you're an asshole

**Comment by oonqt** [comment]
I aint did nun wrong. This aint even me and the original had no reason to continue mantaining
